# -*- coding: utf-8 -*-
"""Proyecto Finanzas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EVp78brN5RgzEgz82BcN3xbwOCl-nMh6
"""

# 3. Descargamos datos históricos del dólar en Chile
# Usamos 'CLP=X' como el ticker para el tipo de cambio USD/CLP.
# Puedes ajustar el rango de fechas según tu interés.
ticker_moneda = "CLP=X" # Ticker para el dólar estadounidense en relación al peso chileno
datos_moneda = yf.download(ticker_moneda, start="2020-01-01", end="2023-12-31")

print(f"Datos descargados para {ticker_moneda}:")
print(datos_moneda.head())

# Configuramos el tamaño del gráfico
plt.figure(figsize=(12, 6))

# Dibujamos la columna del precio de cierre ("Close")
plt.plot(datos_moneda['Close'], color='green', label='Precio de Cierre USD/CLP')

# Agregamos títulos y etiquetas para que parezca un reporte profesional
plt.title('Evolución Histórica del Dólar en Chile', fontsize=16)
plt.xlabel('Fecha', fontsize=12)
plt.ylabel('Precio (CLP)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()

# Mostramos el gráfico
plt.show()

# Importamos numpy, la librería principal para matemáticas y estadística en Python
import numpy as np

# 1. Definimos los fondos a comparar
# SPY = S&P 500 (Mercado Global/EEUU) | ECH = MSCI Chile (Mercado Nacional)
fondos = ['SPY', 'ECH']

# 2. Descargamos la historia de los últimos 4 años
print("Descargando datos del mercado global y nacional...")
datos_fondos = yf.download(fondos, start="2020-01-01")['Close']

# 3. Calculamos los retornos diarios (la base de cualquier predicción financiera)
retornos = datos_fondos.pct_change().dropna()

# 4. Creamos el fundamento fáctico: Retorno Esperado vs Riesgo (anualizado)
rendimiento_anual = retornos.mean() * 252 # 252 días hábiles en la bolsa
riesgo_anual = retornos.std() * np.sqrt(252)

print("\n=== FUNDAMENTO FÁCTICO: RIESGO VS RETORNO ===")
for fondo in fondos:
    print(f"Fondo {fondo}:")
    print(f" - Rendimiento esperado anual: {rendimiento_anual[fondo]*100:.2f}%")
    print(f" - Volatilidad (Riesgo): {riesgo_anual[fondo]*100:.2f}%\n")

# 5. Visualizamos la probabilidad (Campana de Gauss / Histograma)
plt.figure(figsize=(12, 6))
plt.hist(retornos['SPY'], bins=50, alpha=0.6, label='Mercado Global (SPY)', color='blue')
plt.hist(retornos['ECH'], bins=50, alpha=0.6, label='Mercado Chileno (ECH)', color='red')

plt.title('Distribución de Probabilidades: Global vs Nacional', fontsize=16)
plt.xlabel('Retorno Diario (0.01 = 1%)', fontsize=12)
plt.ylabel('Frecuencia (Cantidad de días)', fontsize=12)
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

# Importamos la librería financiera
import yfinance as yf

# Definimos las empresas a analizar (Microdatos)
# AAPL = Apple (EEUU/Global) | SQM = Sociedad Química y Minera (Chile)
activos = {'Apple (Mercado Global)': 'AAPL', 'SQM (Mercado Chileno)': 'SQM'}

print("=== 🧠 MOTOR DE INTELIGENCIA DE NEGOCIOS Y MICRODATOS ===")

for nombre, ticker in activos.items():
    empresa = yf.Ticker(ticker)

    # Extraemos los microdatos en tiempo real (Analítica de Negocios)
    info = empresa.info

    # Variables microeconómicas clave:
    # P/E Ratio: Cuánto paga el mercado por cada dólar de ganancia (Valoración)
    pe_ratio = info.get('forwardPE', 0)

    # Margen Operativo: Eficiencia pura (Fallas de mercado/Poder de monopolio)
    margen_operativo = info.get('operatingMargins', 0) * 100

    # Deuda sobre Capital: Riesgo estructural de quiebra
    riesgo_deuda = info.get('debtToEquity', 0)

    print(f"\n📊 Analizando: {nombre} ({ticker})")
    print(f" - Valoración (P/E Ratio): {pe_ratio:.2f}")
    print(f" - Margen Operativo (Eficiencia): {margen_operativo:.2f}%")
    print(f" - Riesgo de Deuda (Apalancamiento): {riesgo_deuda:.2f}%")

    # =========================================================
    # LÓGICA DE RECOMENDACIÓN (El "Cerebro" Económico de la IA)
    # =========================================================
    puntaje = 0
    fundamentos = []

    # 1. Análisis de Valoración (Evitar burbujas)
    if pe_ratio > 0 and pe_ratio < 25:
        puntaje += 1
        fundamentos.append("Precio atractivo respecto a sus ganancias proyectadas.")
    else:
        fundamentos.append("Alerta: Posible sobrevaloración en el mercado.")

    # 2. Análisis Microeconómico (Poder de mercado)
    if margen_operativo > 20:
        puntaje += 1
        fundamentos.append("Alto poder de mercado (ventaja competitiva fuerte).")
    else:
        fundamentos.append("Márgenes estrechos, alta competencia en su sector.")

    # 3. Análisis de Riesgo Financiero
    if riesgo_deuda < 100:
        puntaje += 1
        fundamentos.append("Nivel de deuda sano y manejable.")
    else:
        fundamentos.append("Alerta: Exceso de endeudamiento, alto riesgo ante subida de tasas.")

    # EMISIÓN DEL DICTAMEN DE OPERACIÓN
    print("\n 💡 RECOMENDACIÓN DE OPERACIÓN:")
    if puntaje == 3:
        print("   ✅ [COMPRA FUERTE] Operación óptima. Sólidos microdatos, bajo riesgo estructural y excelente posición macro.")
    elif puntaje == 2:
        print("   ⚖️ [MANTENER / ACUMULAR] Empresa sólida, pero con un área de riesgo a monitorear.")
    else:
        print("   ❌ [VENDER / NO ENTRAR] Demasiadas debilidades en los microdatos. El riesgo supera la rentabilidad esperada.")

    print("   Fundamentos fácticos de la IA:")
    for razon in fundamentos:
        print(f"   * {razon}")
    print("-" * 60)

# 1. Importamos las herramientas (Incluyendo scikit-learn)
import yfinance as yf
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

print("Iniciando entrenamiento del modelo predictivo...")

# 2. Descargar datos históricos (Usemos SQM como ejemplo)
ticker = "SQM"
data = yf.download(ticker, start="2018-01-01")

# 3. Crear las "Pistas" (Features) que la IA debe estudiar
data['Retorno_Diario'] = data['Close'].pct_change()
data['Media_Movil_5'] = data['Close'].rolling(window=5).mean()
data['Media_Movil_20'] = data['Close'].rolling(window=20).mean()

# 4. Crear el "Objetivo" (Target): 1 si el precio sube mañana, 0 si baja o se mantiene
data['Sube_Manana'] = np.where(data['Close'].shift(-1) > data['Close'], 1, 0)

# Limpiamos los datos vacíos para no confundir a la IA
data = data.dropna()

# 5. Separar los datos en Entrenamiento (Pasado) y Prueba (Futuro cercano)
X = data[['Retorno_Diario', 'Media_Movil_5', 'Media_Movil_20']] # Las pistas
y = data['Sube_Manana'] # Las respuestas correctas

# Le pasamos el 80% de los datos para que "estudie" y guardamos el 20% para tomarle un "examen"
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 6. Crear y entrenar el Cerebro Artificial (Random Forest)
modelo_ia = RandomForestClassifier(n_estimators=100, random_state=42)
modelo_ia.fit(X_train, y_train) # ¡Aquí la IA está aprendiendo matemáticamente sola!

# 7. Evaluar qué tan inteligente se volvió (El Examen)
predicciones_examen = modelo_ia.predict(X_test)
precision = accuracy_score(y_test, predicciones_examen)

print(f"\n🧠 Precisión de la IA en el examen histórico: {precision * 100:.2f}%")

# 8. PREDICCIÓN PARA EL DÍA DE MAÑANA
datos_hoy = X.iloc[-1:] # Tomamos las pistas exactas del día de hoy
prediccion_manana = modelo_ia.predict(datos_hoy)

print("-" * 50)
if prediccion_manana[0] == 1:
    print(f"📈 ALGORITMO PREDICTIVO: La IA proyecta que {ticker} SUBIRÁ en la próxima jornada.")
else:
    print(f"📉 ALGORITMO PREDICTIVO: La IA proyecta que {ticker} BAJARÁ en la próxima jornada.")
print("-" * 50)

# 1. Instalamos la librería financiera (solo toma unos segundos)
!pip install yfinance

# 2. Importamos las herramientas de análisis de datos y gráficos
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

print("¡Librerías instaladas y listas para operar!")

import yfinance as yf
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

print("🌐 Descargando el arsenal de datos (Macroeconomía + Materias Primas)...")

# 1. Definimos nuestro activo principal y nuestras "variables externas"
ticker_objetivo = "SQM"
variables_externas = {
    'Cobre': 'HG=F',       # Futuros del Cobre
    'Litio_ETF': 'LIT',    # ETF de Litio y Baterías
    'Dolar_CLP': 'CLP=X',  # Tipo de cambio Dólar/Peso Chileno
    'SP500': 'SPY'         # Sentimiento del mercado global
}

# 2. Descargamos la data principal
data = yf.download(ticker_objetivo, start="2018-01-01")[['Close']]
data = data.rename(columns={'Close': 'Precio_SQM'})

# 3. Descargamos e integramos las variables externas al mismo DataFrame
for nombre, ticker in variables_externas.items():
    data_externa = yf.download(ticker, start="2018-01-01")[['Close']]
    data[nombre] = data_externa['Close']

# 4. Creamos las "Herramientas" (Features) para la IA
print("⚙️ Procesando indicadores técnicos y correlaciones...")

# Retornos diarios de todos los activos
data['Ret_SQM'] = data['Precio_SQM'].pct_change()
data['Ret_Cobre'] = data['Cobre'].pct_change()
data['Ret_Litio'] = data['Litio_ETF'].pct_change()
data['Ret_Dolar'] = data['Dolar_CLP'].pct_change()
data['Ret_SP500'] = data['SP500'].pct_change()

# Volatilidad y Medias Móviles (Tendencias)
data['Volatilidad_10d'] = data['Ret_SQM'].rolling(window=10).std()
data['Media_Movil_10'] = data['Precio_SQM'].rolling(window=10).mean()
data['Media_Movil_50'] = data['Precio_SQM'].rolling(window=50).mean()

# 5. Definimos el Objetivo (1 = Sube mañana, 0 = Baja/Se mantiene)
data['Sube_Manana'] = np.where(data['Precio_SQM'].shift(-1) > data['Precio_SQM'], 1, 0)

# Limpiamos los datos vacíos generados al cruzar tantas bases de datos
data = data.dropna()

# 6. Separamos en Entrenamiento y Prueba
columnas_pistas = [
    'Ret_SQM', 'Ret_Cobre', 'Ret_Litio',
    'Ret_Dolar', 'Ret_SP500', 'Volatilidad_10d',
    'Media_Movil_10', 'Media_Movil_50'
]

X = data[columnas_pistas]
y = data['Sube_Manana']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 7. Entrenamos un "Cerebro" más potente (Doscientos árboles de decisión)
# Limitamos la profundidad (max_depth) para que la IA no memorice, sino que analice lógicamente
modelo_multivariable = RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42)
modelo_multivariable.fit(X_train, y_train)

# 8. El Examen Final
predicciones = modelo_multivariable.predict(X_test)
precision = accuracy_score(y_test, predicciones)

print("\n" + "="*60)
print(f"🚀 PRECISIÓN DEL MODELO MULTIVARIABLE: {precision * 100:.2f}%")
print("="*60)

# 9. Transparencia de la IA (Feature Importance)
importancias = modelo_multivariable.feature_importances_
print("\n📊 ¿Qué herramientas pesaron más en el cerebro de la IA para decidir?")
for pista, peso in sorted(zip(columnas_pistas, importancias), key=lambda x: x[1], reverse=True):
    print(f" - {pista}: {peso*100:.2f}% de influencia")

# ====================================================================
# MÓDULO DE ASIGNACIÓN DE ACTIVOS (FONDOS MUTUOS, DAP Y ACCIONES)
# ====================================================================

# 1. Definimos las tasas de los instrumentos conservadores
# Como Yahoo Finance no tiene los DAP chilenos, ingresamos la TPM/DAP promedio actual (aprox 6.0%)
tasa_dap_chile = 6.0

# Descargamos la tasa de los Bonos del Tesoro de EEUU a 10 años (El refugio más seguro del mundo)
bono_eeuu = yf.download("^TNX", period="1d", progress=False)['Close'].iloc[-1].item()

# 2. Rescatamos la predicción y el "miedo" desde tu modelo anterior
prediccion = predicciones[0] # 1 si subía, 0 si bajaba
volatilidad_diaria = X_test['Volatilidad_10d'].iloc[-1] * 100 # Pasado a porcentaje

print("🏦 SESIÓN DEL COMITÉ DE INVERSIONES DE LA IA 🏦")
print("-" * 50)
print("Condiciones Macroeconómicas Actuales:")
print(f" - Rendimiento Depósito a Plazo (Chile): {tasa_dap_chile}% anual garantizado")
print(f" - Rendimiento Bono del Tesoro (EEUU): {bono_eeuu:.2f}% anual garantizado")
print(f" - Nivel de Volatilidad / Riesgo (Acciones): {volatilidad_diaria:.2f}%\n")

print("💡 DICTAMEN DE ASIGNACIÓN DE PORTAFOLIO:")

# 3. El Cerebro Asesor: Lógica de diversificación
if prediccion == 1 and volatilidad_diaria < 2.5:
    print("🟢 MERCADO ALCISTA Y TRANQUILO (Modo Agresivo)")
    print(" Estrategia recomendada:")
    print("  * 70% Acciones y ETFs (Renta Variable)")
    print("  * 20% Fondos Mutuos Balanceados (Riesgo Medio)")
    print("  * 10% Liquidez para aprovechar oportunidades")

elif prediccion == 1 and volatilidad_diaria >= 2.5:
    print(f"""🟡 MERCADO ALCISTA PERO MUY VOLÁTIL (Modo Precaución)
 Estrategia recomendada:
  * 40% Fondos Mutuos Estructurados (Protección parcial de capital)
  * 30% Acciones (Solo empresas de alta capitalización, no especulativas)
  * 30% Depósitos a Plazo (Asegurando ese {tasa_dap_chile}% base)""")

else:
    print("🔴 MERCADO BAJISTA O EXTREMADAMENTE PELIGROSO (Modo Refugio)")
    print(" Estrategia recomendada:")
    print(f"  * 70% Depósitos a Plazo en Pesos (Asegurando el {tasa_dap_chile}% anual sin sufrir)")
    print(f"  * 30% Fondos Mutuos de Renta Fija Internacional (Bonos EEUU al {bono_eeuu:.2f}%)")
    print("  * 0% Acciones individuales (Demasiado riesgo de pérdida de capital hoy)")

print("-" * 50)

# ====================================================================
# MÓDULO DE BACKTESTING (SIMULADOR DE RENTABILIDAD CON CAPITAL REAL)
# ====================================================================
import matplotlib.pyplot as plt

# 1. Configuración del Fondo Virtual
capital_inicial = 10000000  # $10.000.000 CLP
comision_broker = 0.001     # 0.1% de comisión por cada operación que hagamos

print(f"💰 INICIANDO BACKTEST: Capital inicial de ${capital_inicial:,.0f} CLP")
print("Viajando en el tiempo para simular operaciones reales...\n")

# 2. Alineamos las predicciones de la IA con la realidad del mercado
df_simulacion = X_test.copy()
# Traemos el retorno real que tuvo SQM esos días
df_simulacion['Retorno_Mercado'] = data.loc[X_test.index, 'Ret_SQM']
# Lo que tu IA dijo que iba a pasar (1 = Sube, 0 = Baja)
df_simulacion['Senal_IA'] = predicciones

# 3. Lógica de Trading Financiero
# Si la IA dice 1, invertimos y ganamos (o perdemos) lo que rinda el mercado.
# Si dice 0, nos quedamos en efectivo (retorno 0).
# Usamos shift(1) porque la decisión de hoy afecta el retorno de mañana.
df_simulacion['Retorno_Estrategia'] = df_simulacion['Senal_IA'].shift(1) * df_simulacion['Retorno_Mercado']

# Aplicamos una penalización por comisión cada vez que la IA cambia de opinión (compra/venta)
df_simulacion['Cambio_Senal'] = df_simulacion['Senal_IA'].diff().abs()
df_simulacion['Retorno_Estrategia'] -= (df_simulacion['Cambio_Senal'] * comision_broker)

# 4. Cálculo del Crecimiento del Dinero (Interés Compuesto)
df_simulacion['Capital_IA'] = capital_inicial * (1 + df_simulacion['Retorno_Estrategia']).cumprod()
df_simulacion['Capital_Buy_Hold'] = capital_inicial * (1 + df_simulacion['Retorno_Mercado']).cumprod()

# 5. Resultados Finales
capital_final_ia = df_simulacion['Capital_IA'].iloc[-1]
capital_final_mercado = df_simulacion['Capital_Buy_Hold'].iloc[-1]
rendimiento_ia = ((capital_final_ia / capital_inicial) - 1) * 100
rendimiento_mercado = ((capital_final_mercado / capital_inicial) - 1) * 100

print("=" * 60)
print("📊 RESULTADOS DEL BACKTESTING (Frente a la Realidad)")
print("=" * 60)
print(f"Estrategia de tu IA      : ${capital_final_ia:,.0f} CLP ({rendimiento_ia:.2f}%)")
print(f"Solo comprar y esperar   : ${capital_final_mercado:,.0f} CLP ({rendimiento_mercado:.2f}%)")
print("-" * 60)

if capital_final_ia > capital_final_mercado:
    print("🏆 DICTAMEN: ¡Excelente! Tu modelo es rentable y logró vencer al mercado.")
else:
    print("⚠️ DICTAMEN: El mercado superó a la IA. Necesitamos modelos más complejos (Redes Neuronales).")

# 6. Graficamos la batalla de rentabilidad
plt.figure(figsize=(12, 6))
plt.plot(df_simulacion.index, df_simulacion['Capital_IA'], label='Capital operado por la IA', color='blue')
plt.plot(df_simulacion.index, df_simulacion['Capital_Buy_Hold'], label='Capital del Mercado (Buy & Hold)', color='gray', alpha=0.6)
plt.title('Batalla de Rentabilidad: IA vs Mercado', fontsize=16)
plt.ylabel('Capital en CLP', fontsize=12)
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

print("⏳ RECALIBRANDO EL TIEMPO: Entrenando cronológicamente...")

# 1. LA CORRECCIÓN CLAVE: shuffle=False (No mezclar el tiempo)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# 2. Re-entrenamos el modelo con la línea de tiempo correcta
modelo_corregido = RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42)
modelo_corregido.fit(X_train, y_train)

# Evaluamos la nueva precisión real
predicciones_reales = modelo_corregido.predict(X_test)
precision_real = accuracy_score(y_test, predicciones_reales)
print(f"🧠 Precisión del modelo en la línea de tiempo real: {precision_real * 100:.2f}%\n")

# ====================================================================
# 3. RE-EJECUTAMOS EL SIMULADOR DE MILLONES (BACKTESTING)
# ====================================================================
capital_inicial = 10000000
comision_broker = 0.001

df_sim = X_test.copy()
df_sim['Retorno_Mercado'] = data.loc[X_test.index, 'Ret_SQM']
df_sim['Senal_IA'] = predicciones_reales

# Lógica de ganancias y comisiones
df_sim['Retorno_Estrategia'] = df_sim['Senal_IA'].shift(1) * df_sim['Retorno_Mercado']
df_sim['Cambio_Senal'] = df_sim['Senal_IA'].diff().abs()
df_sim['Retorno_Estrategia'] -= (df_sim['Cambio_Senal'] * comision_broker)

# Crecimiento del capital
df_sim['Capital_IA'] = capital_inicial * (1 + df_sim['Retorno_Estrategia']).cumprod()
df_sim['Capital_Buy_Hold'] = capital_inicial * (1 + df_sim['Retorno_Mercado']).cumprod()

# Resultados
capital_ia = df_sim['Capital_IA'].iloc[-1]
capital_mercado = df_sim['Capital_Buy_Hold'].iloc[-1]
rendimiento_ia = ((capital_ia / capital_inicial) - 1) * 100
rendimiento_mercado = ((capital_mercado / capital_inicial) - 1) * 100

print("=" * 60)
print("📊 RESULTADOS DEL BACKTESTING CORREGIDO")
print("=" * 60)
print(f"Estrategia de tu IA      : ${capital_ia:,.0f} CLP ({rendimiento_ia:.2f}%)")
print(f"Solo comprar y esperar   : ${capital_mercado:,.0f} CLP ({rendimiento_mercado:.2f}%)")
print("-" * 60)

# 4. El nuevo gráfico ordenado
plt.figure(figsize=(12, 6))
plt.plot(df_sim.index, df_sim['Capital_IA'], label='Capital operado por la IA', color='blue', linewidth=2)
plt.plot(df_sim.index, df_sim['Capital_Buy_Hold'], label='Capital del Mercado (Buy & Hold)', color='gray', alpha=0.6)
plt.title('Batalla de Rentabilidad Cronológica: IA vs Mercado', fontsize=16)
plt.ylabel('Capital en CLP', fontsize=12)
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

# ====================================================================
# PILAR 2: RED NEURONAL LSTM (MEMORIA A LARGO PLAZO)
# ====================================================================
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout

print("🧠 INICIANDO ACTUALIZACIÓN A DEEP LEARNING (LSTM)...")

# 1. Preparación y Escalado (Las Redes Neuronales son muy sensibles a los números grandes)
scaler = MinMaxScaler(feature_range=(0, 1))
X_scaled = scaler.fit_transform(X)

# 2. Creando la "Memoria" (Ventana de tiempo de 30 días)
time_steps = 30

def crear_secuencias(datos, etiquetas, pasos):
    Xs, ys = [], []
    # Convertimos etiquetas a numpy array por seguridad
    etiquetas_np = etiquetas.values if hasattr(etiquetas, 'values') else etiquetas
    for i in range(len(datos) - pasos):
        Xs.append(datos[i:(i + pasos)])      # Toma los últimos 30 días
        ys.append(etiquetas_np[i + pasos])   # Intenta predecir el día 31
    return np.array(Xs), np.array(ys)

X_sec, y_sec = crear_secuencias(X_scaled, y, time_steps)

# 3. División Cronológica Rigurosa (80% Entrenamiento, 20% Examen)
split = int(0.8 * len(X_sec))
X_train_lstm, X_test_lstm = X_sec[:split], X_sec[split:]
y_train_lstm, y_test_lstm = y_sec[:split], y_sec[split:]

print(f"Formato de datos LSTM: {X_train_lstm.shape} -> (Días analizados, Memoria de {time_steps} días, Variables técnicas)\n")

# ====================================================================
# 4. ARQUITECTURA DEL CEREBRO NEURONAL
# ====================================================================
modelo_lstm = Sequential()

# Primera capa LSTM (Aprende patrones complejos de la secuencia)
modelo_lstm.add(LSTM(units=50, return_sequences=True, input_shape=(X_train_lstm.shape[1], X_train_lstm.shape[2])))
modelo_lstm.add(Dropout(0.2)) # "Apaga" 20% de neuronas para que no memorice el pasado de memoria (evita sobreajuste)

# Segunda capa LSTM (Sintetiza la información profunda)
modelo_lstm.add(LSTM(units=50, return_sequences=False))
modelo_lstm.add(Dropout(0.2))

# Capa de Salida (Toma la decisión: 1 = Sube, 0 = Baja)
modelo_lstm.add(Dense(units=1, activation='sigmoid'))

# 5. Compilación del Modelo
modelo_lstm.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 6. Entrenamiento en Vivo
print("⏳ Entrenando la Red Neuronal... (Esto tomará unos segundos en Colab)")
historial = modelo_lstm.fit(
    X_train_lstm, y_train_lstm,
    epochs=20,          # Veces que repasará toda la historia del mercado
    batch_size=32,      # Estudia en bloques de 32 días
    validation_split=0.1,
    verbose=1           # Muestra el progreso en vivo
)
print("\n✅ ¡Entrenamiento completado exitosamente!")

# 7. Evaluación Crítica
loss, precision_lstm = modelo_lstm.evaluate(X_test_lstm, y_test_lstm, verbose=0)
print("-" * 60)
print(f"🎯 Precisión de la Red LSTM en el futuro no visto: {precision_lstm * 100:.2f}%")
print("-" * 60)

# ====================================================================
# SIMULADOR DE CAPITAL PARA LA RED NEURONAL LSTM
# ====================================================================
import pandas as pd
import matplotlib.pyplot as plt

print("💸 CONECTANDO LA RED NEURONAL AL SIMULADOR DE MILLONES...")

# 1. Obtener las predicciones (La LSTM arroja probabilidades, ej: 0.65)
probabilidades = modelo_lstm.predict(X_test_lstm, verbose=0)
# Regla: Si la IA está más de un 50% segura, es 1 (Compra). Si no, 0 (Vende).
predicciones_lstm = (probabilidades > 0.5).astype(int).flatten()

# 2. Alinear los datos de mercado con los días exactos del examen
dias_examen = len(predicciones_lstm)
retornos_reales = data['Ret_SQM'].iloc[-dias_examen:].values

df_lstm = pd.DataFrame({
    'Retorno_Mercado': retornos_reales,
    'Senal_IA': predicciones_lstm
})

# 3. Lógica Financiera (Aplicando comisiones)
capital_inicial = 10000000
comision_broker = 0.001

df_lstm['Retorno_Estrategia'] = df_lstm['Senal_IA'].shift(1) * df_lstm['Retorno_Mercado']
df_lstm['Cambio_Senal'] = df_lstm['Senal_IA'].diff().abs()
df_lstm['Retorno_Estrategia'] -= (df_lstm['Cambio_Senal'] * comision_broker)

# 4. Cálculo del Crecimiento (Interés Compuesto)
df_lstm = df_lstm.fillna(0) # Limpiamos el primer día
df_lstm['Capital_IA'] = capital_inicial * (1 + df_lstm['Retorno_Estrategia']).cumprod()
df_lstm['Capital_Buy_Hold'] = capital_inicial * (1 + df_lstm['Retorno_Mercado']).cumprod()

# 5. Resultados Finales
cap_final_lstm = df_lstm['Capital_IA'].iloc[-1]
cap_final_mercado = df_lstm['Capital_Buy_Hold'].iloc[-1]
rend_lstm = ((cap_final_lstm / capital_inicial) - 1) * 100
rend_mercado = ((cap_final_mercado / capital_inicial) - 1) * 100

print("\n" + "=" * 60)
print("📊 RESULTADOS DEL BACKTESTING: DEEP LEARNING (LSTM)")
print("=" * 60)
print(f"Estrategia Red Neuronal  : ${cap_final_lstm:,.0f} CLP ({rend_lstm:.2f}%)")
print(f"Solo comprar y esperar   : ${cap_final_mercado:,.0f} CLP ({rend_mercado:.2f}%)")
print("-" * 60)

# 6. Gráfico de la Batalla
plt.figure(figsize=(12, 6))
plt.plot(df_lstm.index, df_lstm['Capital_IA'], label='Capital Operado por IA (LSTM)', color='purple', linewidth=2)
plt.plot(df_lstm.index, df_lstm['Capital_Buy_Hold'], label='Capital del Mercado', color='gray', alpha=0.6)
plt.title('Batalla de Rentabilidad: Red Neuronal LSTM vs Mercado', fontsize=16)
plt.ylabel('Capital en CLP', fontsize=12)
plt.xlabel('Días operados (Futuro no visto por la IA)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

# ====================================================================
# PILAR 3: NLP Y SENTIMIENTO DE MERCADO CON FINBERT
# ====================================================================
# (Descomenta la siguiente línea y ejecútala una vez si Colab te pide instalar transformers)
# !pip install transformers

from transformers import pipeline
import pandas as pd

print("🧠 CARGANDO 'FINBERT' - EL CEREBRO LECTOR DE WALL STREET...")
print("Descargando pesos neuronales... (Esto puede tomar 1-2 minutos la primera vez)")

# 1. Cargar el modelo especializado en Finanzas
# Usamos el modelo de ProsusAI entrenado para clasificar: Positivo, Negativo o Neutral
analista_nlp = pipeline("sentiment-analysis", model="ProsusAI/finbert")

# 2. Simulación de Titulares (News Feed)
# En un entorno de producción, esto se conecta a una API de noticias (ej. Bloomberg, Reuters)
titulares_hoy = [
    "SQM reports record breaking revenues due to high global lithium demand.",
    "Chilean government considers new regulatory taxes on lithium extraction.",
    "Global markets crash as inflation fears rise unexpectedly.",
    "Battery manufacturers secure long-term supply contracts with SQM.",
    "Trading volume remains steady amid quiet market session."
]

print("\n📰 LEYENDO LAS NOTICIAS DE HOY:")
print("-" * 60)

# 3. Procesamiento y Traducción a Matemáticas (Sentiment Scoring)
resultados_sentimiento = []

for titular in titulares_hoy:
    # La IA lee el titular y emite un juicio
    analisis = analista_nlp(titular)[0]
    etiqueta = analisis['label'] # positive, negative, neutral
    certeza = analisis['score']  # Qué tan segura está la IA (0.0 a 1.0)

    # Convertimos el texto a números para que el modelo LSTM lo entienda después:
    # Positivo = +1, Neutral = 0, Negativo = -1
    if etiqueta == 'positive':
        score_numerico = certeza
    elif etiqueta == 'negative':
        score_numerico = -certeza
    else:
        score_numerico = 0

    resultados_sentimiento.append({
        'Titular': titular,
        'Sentimiento': etiqueta.upper(),
        'Score_Matematico': round(score_numerico, 3)
    })

# 4. Mostrar el reporte de la IA
df_noticias = pd.DataFrame(resultados_sentimiento)

for index, row in df_noticias.iterrows():
    if row['Score_Matematico'] > 0:
        emoji = "🟢"
    elif row['Score_Matematico'] < 0:
        emoji = "🔴"
    else:
        emoji = "⚪"

    print(f"{emoji} {row['Sentimiento']} (Score: {row['Score_Matematico']})")
    print(f"   > {row['Titular']}\n")

print("-" * 60)
print("💡 DATO QUANT: Este 'Score_Matematico' es la nueva variable que le inyectaremos a tu LSTM.")

# ====================================================================
# PILAR 4: EL SUPER-MODELO (LSTM + NLP SENTIMENT)
# ====================================================================
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout

print("🚀 CONSTRUYENDO EL SUPER-MODELO (TÉCNICO + MACRO + NLP)...")

# 1. Simulación de la base de datos histórica de noticias
# (En producción, aquí harías pd.merge() con tus scores reales de FinBERT)
np.random.seed(42) # Para que obtengamos los mismos resultados
ruido_noticias = np.random.normal(0, 0.4, len(data))

# Creamos la columna imitando cómo las noticias reaccionan al mercado (con un grado de aleatoriedad)
# Limitamos los valores entre -1 (Pánico extremo) y 1 (Euforia extrema)
data['Sentimiento_FinBERT'] = np.clip((data['Ret_SQM'] * 15) + ruido_noticias, -1, 1)

# 2. Agregar la nueva "variable psicológica" a nuestras características
# Juntamos todas las variables que ya tenías, MÁS el sentimiento.

# Define the base technical and macroeconomic features used by previous models
# This list comes from 'columnas_pistas' defined in cell ornHkEz-YxIg
base_features_for_super_model = [
    'Ret_SQM', 'Ret_Cobre', 'Ret_Litio', 'Ret_Dolar', 'Ret_SP500',
    'Volatilidad_10d', 'Media_Movil_10', 'Media_Movil_50'
]

# Add the new sentiment feature to the base features
columnas_finales = base_features_for_super_model + ['Sentimiento_FinBERT']

X_super = data[columnas_finales].values
y_super = data['Sube_Manana'].values # Corrected: Use 'Sube_Manana' as the target

print(f"📊 Variables inyectadas a la IA: {columnas_finales}")

# 3. Escalado y Secuencias Temporales (Memoria de 30 días)
scaler_super = MinMaxScaler(feature_range=(0, 1))
X_super_scaled = scaler_super.fit_transform(X_super)

X_sec_nlp, y_sec_nlp = crear_secuencias(X_super_scaled, y_super, pasos=30)

# 4. División de Entrenamiento y Prueba (Cronológica)
split_nlp = int(0.8 * len(X_sec_nlp))
X_train_nlp, X_test_nlp = X_sec_nlp[:split_nlp], X_sec_nlp[split_nlp:]
y_train_nlp, y_test_nlp = y_sec_nlp[:split_nlp], y_sec_nlp[split_nlp:]

print(f"\n🧠 Formato del Cerebro: {X_train_nlp.shape}")
print("(Días entrenados, 30 días de memoria, Cantidad de variables incluyendo NLP)")

# 5. La Arquitectura del Super-Modelo (Un poco más robusto para procesar NLP)
super_modelo = Sequential()
super_modelo.add(LSTM(units=60, return_sequences=True, input_shape=(X_train_nlp.shape[1], X_train_nlp.shape[2])))
super_modelo.add(Dropout(0.2))
super_modelo.add(LSTM(units=60, return_sequences=False))
super_modelo.add(Dropout(0.2))
super_modelo.add(Dense(units=1, activation='sigmoid')) # Decisión final: 1 o 0

super_modelo.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 6. Entrenamiento en Vivo
print("\n⏳ Entrenando la Red Neuronal Definitiva... (Observa la precisión)")
historial_super = super_modelo.fit(
    X_train_nlp, y_train_nlp,
    epochs=20,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)
print("\n✅ ¡SUPER-MODELO ENTRENADO EXITOSAMENTE!")

# ====================================================================
# SIMULADOR FINAL: SUPER-MODELO VS MERCADO
# ====================================================================
import pandas as pd
import matplotlib.pyplot as plt

print("💸 PRUEBA FINAL: CONECTANDO EL SUPER-MODELO AL MERCADO REAL...")

# 1. Obtener predicciones del Super-Modelo (Arroja probabilidades 0.0 a 1.0)
probabilidades_super = super_modelo.predict(X_test_nlp, verbose=0)
predicciones_super = (probabilidades_super > 0.5).astype(int).flatten()

# 2. Alinear los datos temporales
# Tomamos exactamente los retornos reales de los últimos días que la IA rindió examen
dias_examen_super = len(predicciones_super)
retornos_reales_super = data['Ret_SQM'].iloc[-dias_examen_super:].values

df_super = pd.DataFrame({
    'Retorno_Mercado': retornos_reales_super,
    'Senal_IA': predicciones_super
})

# 3. Lógica Financiera (Aplicando el mundo real y comisiones)
capital_inicial = 10000000
comision_broker = 0.001

df_super['Retorno_Estrategia'] = df_super['Senal_IA'].shift(1) * df_super['Retorno_Mercado']
df_super['Cambio_Senal'] = df_super['Senal_IA'].diff().abs()
df_super['Retorno_Estrategia'] -= (df_super['Cambio_Senal'] * comision_broker)

# 4. Cálculo del Crecimiento de Capital (Interés Compuesto)
df_super = df_super.fillna(0) # Limpieza del primer día
df_super['Capital_IA_Super'] = capital_inicial * (1 + df_super['Retorno_Estrategia']).cumprod()
df_super['Capital_Buy_Hold'] = capital_inicial * (1 + df_super['Retorno_Mercado']).cumprod()

# 5. Veredicto Final
cap_final_super = df_super['Capital_IA_Super'].iloc[-1]
cap_final_mercado = df_super['Capital_Buy_Hold'].iloc[-1]
rend_super = ((cap_final_super / capital_inicial) - 1) * 100
rend_mercado = ((cap_final_mercado / capital_inicial) - 1) * 100

print("\n" + "=" * 60)
print("🏆 RESULTADOS DEL BACKTESTING DEFINITIVO (LSTM + NLP)")
print("=" * 60)
print(f"Estrategia SUPER-MODELO  : ${cap_final_super:,.0f} CLP ({rend_super:.2f}%)")
print(f"Solo comprar y esperar   : ${cap_final_mercado:,.0f} CLP ({rend_mercado:.2f}%)")
print("-" * 60)

if cap_final_super > cap_final_mercado:
    print("👑 ¡HISTÓRICO! Tu IA venció al mercado combinando Macroeconomía y Análisis de Sentimiento.")
else:
    print("🛡️ El mercado subió más rápido, pero revisa el gráfico: ¿la IA protegió tu capital en las caídas?")

# 6. El Gráfico de la Verdad
plt.figure(figsize=(12, 6))
plt.plot(df_super.index, df_super['Capital_IA_Super'], label='IA Definitiva (LSTM + NLP)', color='gold', linewidth=2.5)
plt.plot(df_super.index, df_super['Capital_Buy_Hold'], label='Mercado (Buy & Hold)', color='gray', alpha=0.6)
plt.title('La Batalla Final: Super-Modelo vs Mercado', fontsize=16)
plt.ylabel('Capital en CLP', fontsize=12)
plt.xlabel('Días operados (Futuro no visto por la IA)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

# ====================================================================
# SIMULADOR FINAL: SUPER-MODELO VS MERCADO
# ====================================================================
import pandas as pd
import matplotlib.pyplot as plt

print("💸 PRUEBA FINAL: CONECTANDO EL SUPER-MODELO AL MERCADO REAL...")

# 1. Obtener predicciones del Super-Modelo (Arroja probabilidades 0.0 a 1.0)
probabilidades_super = super_modelo.predict(X_test_nlp, verbose=0)
predicciones_super = (probabilidades_super > 0.5).astype(int).flatten()

# 2. Alinear los datos temporales
# Tomamos exactamente los retornos reales de los últimos días que la IA rindió examen
dias_examen_super = len(predicciones_super)
retornos_reales_super = data['Ret_SQM'].iloc[-dias_examen_super:].values

df_super = pd.DataFrame({
    'Retorno_Mercado': retornos_reales_super,
    'Senal_IA': predicciones_super
})

# 3. Lógica Financiera (Aplicando el mundo real y comisiones)
capital_inicial = 10000000
comision_broker = 0.001

df_super['Retorno_Estrategia'] = df_super['Senal_IA'].shift(1) * df_super['Retorno_Mercado']
df_super['Cambio_Senal'] = df_super['Senal_IA'].diff().abs()
df_super['Retorno_Estrategia'] -= (df_super['Cambio_Senal'] * comision_broker)

# 4. Cálculo del Crecimiento de Capital (Interés Compuesto)
df_super = df_super.fillna(0) # Limpieza del primer día
df_super['Capital_IA_Super'] = capital_inicial * (1 + df_super['Retorno_Estrategia']).cumprod()
df_super['Capital_Buy_Hold'] = capital_inicial * (1 + df_super['Retorno_Mercado']).cumprod()

# 5. Veredicto Final
cap_final_super = df_super['Capital_IA_Super'].iloc[-1]
cap_final_mercado = df_super['Capital_Buy_Hold'].iloc[-1]
rend_super = ((cap_final_super / capital_inicial) - 1) * 100
rend_mercado = ((cap_final_mercado / capital_inicial) - 1) * 100

print("\n" + "=" * 60)
print("🏆 RESULTADOS DEL BACKTESTING DEFINITIVO (LSTM + NLP)")
print("=" * 60)
print(f"Estrategia SUPER-MODELO  : ${cap_final_super:,.0f} CLP ({rend_super:.2f}%)")
print(f"Solo comprar y esperar   : ${cap_final_mercado:,.0f} CLP ({rend_mercado:.2f}%)")
print("-" * 60)

if cap_final_super > cap_final_mercado:
    print("👑 ¡HISTÓRICO! Tu IA venció al mercado combinando Macroeconomía y Análisis de Sentimiento.")
else:
    print("🛡️ El mercado subió más rápido, pero revisa el gráfico: ¿la IA protegió tu capital en las caídas?")

# 6. El Gráfico de la Verdad
plt.figure(figsize=(12, 6))
plt.plot(df_super.index, df_super['Capital_IA_Super'], label='IA Definitiva (LSTM + NLP)', color='gold', linewidth=2.5)
plt.plot(df_super.index, df_super['Capital_Buy_Hold'], label='Mercado (Buy & Hold)', color='gray', alpha=0.6)
plt.title('La Batalla Final: Super-Modelo vs Mercado', fontsize=16)
plt.ylabel('Capital en CLP', fontsize=12)
plt.xlabel('Días operados (Futuro no visto por la IA)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

!pip install alpaca-py

from alpaca.trading.client import TradingClient

# Tus credenciales de Paper Trading
API_KEY = "PKQGEEG4UCGEWHMOH3EJGSRJQL"
SECRET_KEY = "Hk7A5vXQ5TUVarzr8wtP4fK4KN3tP8PtEpqti8ebRBHa"

# Conectamos al servidor de simulación
client = TradingClient(API_KEY, SECRET_KEY, paper=True)

# Solicitamos el estado actual de tu cuenta
cuenta = client.get_account()

print("¡Conexión establecida con éxito con Alpaca!")
print(f"Estado de la cuenta : {cuenta.status}")
print(f"Efectivo disponible : ${float(cuenta.cash):,.2f} USD")
print(f"Poder de compra     : ${float(cuenta.buying_power):,.2f} USD")


from alpaca.trading.requests import MarketOrderRequest
from alpaca.trading.enums import OrderSide, TimeInForce

# Suponiendo que tu modelo acaba de dar la señal de hoy:
# (1 = Comprar, 0 = Esperar/Vender)
senal_hoy = 1  # Esto vendría de tu predicción de la Red Neuronal

if senal_hoy == 1:
    # Preparamos una orden de compra fraccionada (ideal para tus montos chicos)
    orden_datos = MarketOrderRequest(
        symbol="SQM",
        notional=50, # Puedes invertir desde $10 o $50 dólares fraccionados
        side=OrderSide.BUY,
        time_in_force=TimeInForce.DAY
    )

    # Enviamos la orden al broker de prueba
    orden = client.submit_order(order_data=orden_datos)
    print("🚀 ¡Orden ejecutada con éxito en Alpaca!")
    print(f"Detalles de la orden: {orden.id} - Símbolo: SQM")
else:
    print("🛡️ La IA prefiere liquidez hoy. No se envían órdenes.")